site_name: CodeSpree
site_description: Learn Programming with Kuai - Tutorials and Exercises.
site_author: Kuai Yu
site_url: https://yukuairoy.github.io/codespree/
repo_url: https://github.com/yukuairoy/codespree
theme:
  name: material
  favicon: images/favicon.jpeg
  features:
    - navigation.expand
  logo: images/favicon.jpeg
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  custom_dir: overrides
  hljs_languages:
    - yaml
    - python
    - javascript
    - django

nav:
  - Home: index.md
  - Exercises:
      - Programming Exercises: Exercises/programming_exercises.md
      - Mini-Projects: Exercises/mini_projects.md
  - Python 101:
      - Python Basics: Python101/Python_Basics.md
      - Control Flow: Python101/Control_Flow.md
      - OOP: Python101/Object_Oriented_Programming.md
      - Managing Imports: Python101/Managing_Imports.md
      - Dependency Management: Python101/pip.md
  - Miscellaneous:
      - Ciphers: Miscellaneous/ciphers/ciphers.md
      - Trees: 
          - Trees and Forests: Miscellaneous/trees/trees_and_forests.md
          - Rooted Trees: Miscellaneous/trees/rooted_tree.md
          - k-ary Trees: Miscellaneous/trees/k_ary_tree.md
      - The Birthday Problem: Miscellaneous/birthday/birthday.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
      linenums: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - minify:
      minify_html: true
  - social

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kuai/
    - icon: fontawesome/brands/github
      link: https://www.github.com/yukuairoy
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/realkuaiyu

copyright: Copyright &copy; 2024 <a href="https://www.linkedin.com/in/kuai/">Kuai Yu</a>, All Rights Reserved.